/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutIcon: typeof import('./src/components/icons/header-bar/AboutIcon.vue')['default']
    BlogIcon: typeof import('./src/components/icons/header-bar/BlogIcon.vue')['default']
    CaseIcon: typeof import('./src/components/icons/header-bar/CaseIcon.vue')['default']
    copy: typeof import('./src/components/icons/header-bar/ToolsIcon copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElInput: typeof import('element-plus/es')['ElInput']
    FriendIcon: typeof import('./src/components/icons/header-bar/FriendIcon.vue')['default']
    GithubIcon: typeof import('./src/components/icons/header-bar/GithubIcon.vue')['default']
    LabIcon: typeof import('./src/components/icons/header-bar/LabIcon.vue')['default']
    LinkIcon: typeof import('./src/components/icons/header-bar/LinkIcon.vue')['default']
    MessageIcon: typeof import('./src/components/icons/header-bar/MessageIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolsIcon: typeof import('./src/components/icons/header-bar/ToolsIcon.vue')['default']
    ZmCard: typeof import('./src/components/zm-card/index.vue')['default']
  }
}
